#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "answer"
name = "Answer"
description.en = "Knowledge-based community software"
description.fr = "Logiciel communautaire basé sur la connaissance"

version = "1.4.2~ynh1"

maintainers = []

[upstream]
license = "Apache-2.0"
website = "https://answer.apache.org/"
admindoc = "https://answer.apache.org/docs"
code = "https://github.com/apache/answer"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["fr", "en"]
    default = "fr"

    [install.admin]
    type = "user"

    [install.password]
    help.en = "Use the help field to add an information for the admin about this question."
    help.fr = "Utilisez le champ aide pour ajouter une information à l'intention de l'administrateur à propos de cette question."
    type = "password"

[resources]

    [resources.sources]

    [resources.sources.main]
    amd64.url = "https://github.com/apache/answer/releases/download/v1.4.2/apache-answer-1.4.2-bin-linux-amd64.tar.gz"
    amd64.sha256 = "af8be8615a2483312ffd3b17f6e3dfb8cf37bdd5fc62d9e5bb8b98b4b417f686"
    arm64.url = "https://github.com/apache/answer/releases/download/v1.4.2/apache-answer-1.4.2-bin-linux-arm64.tar.gz"
    arm64.sha256 = "14e616e1f45a842c13463beb1de07b10ba788f1310ef7c4793ba3efeed5d1817"
    
    # autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]
    subdirs = [ "cache", "conf", "i18n" ]

    [resources.permissions]
    main.url = "/"

    [resources.ports]

    [resources.apt]
    packages = "postgresql"

    [resources.database]
    type = "postgresql"
