server:
  http:
    addr: 127.0.0.1:__PORT__ # Project access port number
data:
  database:
    driver: "mysql" # Default database driver is mysql
    connection: __DB_USER__:__DB_PWD__@tcp(127.0.0.1:3306)/__DB_NAME__ # MySQL database connection address
  cache:
    file_path: "__DATADIR__/cache/cache.db" # Cache file storage path
i18n:
  bundle_dir: "__DATADIR__/i18n" # Internationalized file storage directory
swaggerui:
  show: true # Whether to display the swaggerapi documentation, address /swagger/index.html
  protocol: http # swagger protocol header
  host: 127.0.0.1 # An accessible IP address or domain name
  address: ':__PORT__'  # accessible port number
service_config:
  secret_key: "answer" # encryption key
  upload_path: "__DATADIR__/uploads" # upload directory
  