server:
  http:
    addr: 127.0.0.1:__PORT__ # Project access port number
data:
  database:
    driver: "postgresql" # Default database driver is mysql
    connection: __DB_USER__:__DB_PWD__@localhost/__DB_NAME__
  cache:
    file_path: "/tmp/cache/cache.db" # Cache file storage path
i18n:
  bundle_dir: "/data/i18n" # Internationalized file storage directory
swaggerui:
  show: true # Whether to display the swaggerapi documentation, address /swagger/index.html
  protocol: http # swagger protocol header
  host: 127.0.0.1 # An accessible IP address or domain name
  address: ':__PORT__'  # accessible port number
service_config:
  upload_path: "/data/uploads" # upload directory
ui:
  public_url: '/' # static resource path
  api_url: '/' # api url for  ajax requests
  base_url: ''  # the default deployment is in the root directory, you need to change this value when deploying in a subdirectory